name: BanHammer
main: name.richardson.james.banhammer.BanHammer
version: 1.5.0
database: true
commands:
  kick:
    description: 'Kicks a specified player from the server.'
    usage: '/kick [player] <reason>'
  ban:
    description: 'Bans a specified player from the server.'
    usage: '/ban [player] [reason] <time>'
  pardon:
    description: 'Pardons a specified player'
    usage: '/pardon [player]'
  bh:
    description: 'Additional ban commands'
    usage: '/bh [check|history|purge|recent|reload]'
