name: BanHammer
main: name.richardson.james.banhammer.BanHammer
version: 1.1.1
database: true
commands:
  kick:
    description: 'Kicks a specified player from the server.'
    usage: '/kick [player] <reason>'
  ban:
    description: 'Bans a specified player from the server.'
    usage: '/ban <-f> [player] [reason]'
  tempban:
    description: 'Bans a specified player for a specified amount of time.'
    usage: '/tempban <-f> [player] [time] [unit] [reason]'
  pardon:
    description: 'Pardons a specified player'
    usage: '/pardon <-aA> [player]'
  bh:
    description: 'Additional ban commands'
    usage: '/bh [history|check|purge]'
