name: BanHammer
main: name.richardson.james.banhammer.BanHammer
version: 1.0.1
database: true
commands:
  kick:
    description: 'Kicks a specified player from the server.'
    usage: '/kick [player]'
  ban:
    description: 'Bans a specified player from the server.'
    usage: '/ban <-tpf> [player]'
  pardon:
    description: 'Pardons a specified player'
    usage: '/pardon <-aA> [player]'
  banhistory:
    description: 'Display all bans associated with a specific player'
    usage: '/banhistory <-aA> [player]'
